const types = {
  GET_EVENT: 'GET_EVENT',
  GET_EVENT_START: 'GET_EVENT_START',
  GET_EVENT_FINISHED: 'GET_EVENT_FINISHED',
  GET_EVENT_ERROR: 'GET_EVENT_ERROR',

  GET_EVENT_INFO: 'GET_EVENT_INFO',
  GET_EVENT_INFO_START: 'GET_EVENT_INFO_START',
  GET_EVENT_INFO_FINISHED: 'GET_EVENT_INFO_FINISHED',
  GET_EVENT_INFO_ERROR: 'GET_EVENT_INFO_ERROR',

  CREATE_EVENT: 'CREATE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',

  CREATE_EVENT_START: 'CREATE_EVENT_START',
  CREATE_EVENT_FINISHED: 'CREATE_EVENT_FINISHED',
  CREATE_EVENT_ERROR: 'CREATE_EVENT_ERROR',

  REJECT_EVENT: 'REJECT_EVENT',
  ACCEPT_EVENT: 'ACCEPT_EVENT',
};
export default types;
