default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "OpenInvite.xcodeproj")
    build_app(workspace: "OpenInvite.xcworkspace", scheme: "OpenInvite", export_xcargs: "-allowProvisioningUpdates")

  end
  lane :testFlight_upload do
    upload_to_testflight
  end
end