const types = {
  SHARE_LINK_OPEN: 'SHARE_LINK_OPEN',
  SHARE_LINK_CLOSE: 'SHARE_LINK_CLOSE',
  UPDATE_LOCATION: 'UPDATE_LOCATION',
  UPDATE_LOCATION_FINISHED: 'UPDATE_LOCATION_FINISHED',
  LISTEN_UNREAD_MSG: 'LISTEN_UNREAD_MSG',
  UPDATE_UNREAD_MSG: 'UPDATE_UNREAD_MSG',
};
export default types;
