const types = {
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  GET_NOTIFICATIONS_START: 'GET_NOTIFICATIONS_START',
  GET_NOTIFICATIONS_FINISHED: 'GET_NOTIFICATIONS_FINISHED',
  GET_NOTIFICATIONS_ERROR: 'GET_NOTIFICATIONS_ERROR',

  GET_NOTIFICATIONS_COUNT_START: 'GET_NOTIFICATIONS_COUNT_START',
  GET_NOTIFICATIONS_COUNT_FINISHED: 'GET_NOTIFICATIONS_COUNT_FINISHED',
  GET_NOTIFICATIONS_COUNT_ERROR: 'GET_NOTIFICATIONS_COUNT_ERROR',
  GET_NOTIFICATIONS_COUNT: 'GET_NOTIFICATIONS_COUNT',
  SET_NOTIFICATION_TO_READ: 'SET_NOTIFICATION_TO_READ',
};
export default types;
